// react/docs/src/app/views/cdk/Categories/Categories.tsx
import React from 'react';
import { useHistory } from 'react-router-dom';

import MlCard from '../../../../material-lite/react/Card';

const Categories = () => {
  const history = useHistory();

  const navRoute = (name: string) => {
    history.push('/react/cdk/' + name);
  }

  return (
    <div className="app-categories">
      <h1>Categories</h1>

      <MlCard variant="stroked" onClick={() => navRoute('straight-tracker')}>
        <div className="app-categories-title">Straight-tracker</div>
      </MlCard>

      <div className="ml-card"></div>
      <div className="ml-card"></div>
      <div className="ml-card"></div>
    </div>
  );
}

export default Categories;

// angular/docs/src/app/views/cdk/categories/categories.component.ts
import { Component, OnInit, ViewEncapsulation } from '@angular/core';

@Component({
  selector: 'app-categories',
  templateUrl: './categories.component.html',
  encapsulation: ViewEncapsulation.None,
  host: {'class': 'app-categories'}
})
export class CategoriesComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}

<h1>CDK</h1>

<ml-card variant="stroked" routerLink="/cdk/portal">
  <div class="app-categories-title">Portal</div>
</ml-card>

<ml-card variant="stroked" routerLink="/cdk/straight-tracker">
  <div class="app-categories-title">Straight Tracker</div>
</ml-card>

<div class="ml-card"></div>
<div class="ml-card"></div>
