// react/docs/src/app/views/components/Button/Button.tsx
import React from 'react';
import { Redirect, Route, Switch, useRouteMatch } from 'react-router-dom';
import DocsNavbar from 'components/DocsNavbar';
import { Examples, Overview, Reference } from './pages';

export const Button = () => {
  const match = useRouteMatch();

  return (
    <div className="docs-view">
      <DocsNavbar></DocsNavbar>

      <h1>Button<code>- Directive</code></h1>

      <Switch>
        <Redirect path={match.url} to={`${match.url}/overview`} exact></Redirect>
        <Route path={`${match.url}/overview`} component={Overview}></Route>
        <Route path={`${match.url}/reference`} component={Reference}></Route>
        <Route path={`${match.url}/examples`} component={Examples}></Route>
      </Switch>
    </div>
  );
}

export default Button;

// vue3/docs/src/views/Components/Button/Button.vue
<template>
  <h1>Button<code>- [mlButton]</code></h1>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import { useRoute } from 'vue-router';
import { Overview, Reference, Example } from './Pages';

export default defineComponent({
  name: 'Button',
  setup() {
    const route = useRoute();
    console.log(route.params.id)
  },
  components: {
  }
});
</script>


<style lang="scss">
</style>
