// angular/docs/src/material-lite/angular/button/button.component.ts
import { DOCUMENT } from '@angular/common';
import {
  ChangeDetectionStrategy, Component, ElementRef, Inject,
  Input, OnChanges, OnInit, ViewChild, ViewEncapsulation
} from '@angular/core';
import { RunOutsideNgZone, RUN_OUTSIDE_NG_ZONE, Falsy, MlDocument } from 'src/material-lite/angular-cdk/utils';
import { mixinBundleFactory, mixinDisableRipple, mixinRippleDynamicConfig, mixinTheme, MlRippleCore } from 'src/material-lite/angular/core';

export type MlButtonVariant = 'basic' | 'raised' | 'stroked' | 'flat' | 'fab' | 'icon';
export type MlButtonHoverAction = 'enabled' | 'disabled' | 'auto';

const ButtonMixin = mixinBundleFactory(mixinDisableRipple, mixinRippleDynamicConfig, mixinTheme);

@Component({
  selector: '[mlButton]',
  exportAs: 'mlButton',
  templateUrl: './button.component.html',
  inputs: ['theme', 'disableRipple', 'rippleConfig'],
  host: {class: 'ml-button'},
  styleUrls: ['./button.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None
})
export class MlButton extends ButtonMixin implements OnInit, OnChanges {
  readonly isButtonElement: boolean;

  private _needSetVariant: boolean = true;

  private _currentClassList: string[] = [];

  @Input('disabled') set setDisabled(isDisabled: true | Falsy) {
    // @ts-expect-error Assign to readonly variable
    const result = this.disabled =
      isDisabled || isDisabled === '';

    const el = this._elementRef.nativeElement as HTMLButtonElement;

    if (result) {
      el.classList.add('ml-disabled');
      this.disableRipple = true;

      if (this.isButtonElement) {
        el.disabled = true;
      }

    } else {
      el.classList.remove('ml-disabled');
      this.disableRipple = false;

      if (this.isButtonElement) {
        el.disabled = false;
      }
    }
  }
  readonly disabled: boolean = false;

  @Input('variant') set setVariant(variant: MlButtonVariant) {
    // @ts-expect-error Assign to readonly variable
    this.variant = variant;
    this._needSetVariant = true;
  }
  readonly variant: MlButtonVariant;

  @Input('hoverAction') set setHoverAction(type: MlButtonHoverAction) {
    // @ts-expect-error Assign to readonly variable
    this.hoverAction = type;
    this._needSetVariant = true;
  }
  readonly hoverAction: MlButtonHoverAction;

  @Input('wrappedAnchor') set setAnchorToWrapped(isEnabled: true | Falsy) {
    // @ts-expect-error Assign to readonly variable
    const result = this.hasWrappedAnchor =
      isEnabled || isEnabled === '';

    const classList = this._elementRef.nativeElement.classList;

    result
      ? classList.add('ml-anchor-button')
      : classList.remove('ml-anchor-button');
  }
  readonly hasWrappedAnchor: boolean;

  readonly rippleCore: MlRippleCore;
  private _rippleCoreFactory: ((outletEl: HTMLElement) => MlRippleCore) | null;

  @ViewChild('mlRippleOutlet', { static: true })
  private set _setRippleCore(outletElementRef: ElementRef<HTMLElement>) {
    // @ts-expect-error: Assign to readonly variable
    const core = this.rippleCore = this._rippleCoreFactory(outletElementRef.nativeElement);
    this._rippleCoreFactory = null;

    core.presetTrigger(this._elementRef.nativeElement);
  }

  constructor(
    protected _elementRef: ElementRef<HTMLElement>,
    @Inject(RUN_OUTSIDE_NG_ZONE) runOutsideNgZone: RunOutsideNgZone,
    @Inject(DOCUMENT) _document: MlDocument,
  ) {
    super();

    const el = this._elementRef.nativeElement;

    const isButtonEl = this.isButtonElement = el instanceof HTMLButtonElement;
    if (!isButtonEl) {
      el.addEventListener('click', this._haltDisabledEvents.bind(this));
    }

    const dynamicConfig = this._rippleDynamicConfig;
    dynamicConfig._dynamic.animation = {
      enter: 280,
      leave: 240
    }

    this._rippleCoreFactory = (outletEl) =>
      new MlRippleCore(
        dynamicConfig, outletEl, runOutsideNgZone,
        _document.createElement.bind(_document), true
      );
  }

  ngOnInit(): void {
    // Rippleが設定されていないとき
    if (this.rippleIsDisabled === void 0) {
      this.rippleCore.setup();
    }

    this.ngOnChanges();
  }

  ngOnChanges(): void {
    if (this._needSetVariant) {
      this._needSetVariant = false;

      const hostClassList = this._elementRef.nativeElement.classList;
      const v = this.variant;
      hostClassList.remove(...this._currentClassList);

      if (!v || v === 'basic') {
        this._currentClassList = [
          'ml-basic-button',
          'ml-simple-button',
        ];
        this._rippleDynamicConfig._dynamic.entrance = null;
        this._enableHoverAction();

      } else if (v === 'raised') {
        this._currentClassList = [
          'ml-raised-button',
          'ml-filled-button'
        ];
        this._rippleDynamicConfig._dynamic.entrance = null;
        this._disableHoverAction();

      } else if (v === 'icon') {
        this._currentClassList = [
          'ml-icon-button',
          'ml-simple-button'
        ];
        this._rippleDynamicConfig._dynamic.entrance = 'center';
        this._disableHoverAction();

      } else if (v === 'fab') {
        this._currentClassList = [
          'ml-fab',
          'ml-filled-button'
        ];
        this._rippleDynamicConfig._dynamic.entrance = null;
        this._disableHoverAction();

      } else if (v === 'flat') {
        this._currentClassList = [
          'ml-flat-button',
          'ml-filled-button'
        ];
        this._rippleDynamicConfig._dynamic.entrance = null;
        this._disableHoverAction();

      } else if (v === 'stroked') {
        this._currentClassList = [
          'ml-stroked-button',
          'ml-simple-button',
        ];
        this._rippleDynamicConfig._dynamic.entrance = null;
        this._enableHoverAction();

      } else {
        this._currentClassList = [
          'ml-basic-button',
          'ml-simple-button',
        ];
        this._rippleDynamicConfig._dynamic.entrance = null;
        this._enableHoverAction();
      }

      hostClassList.add(...this._currentClassList);
    }
  }

  private _enableHoverAction(): void {
    if (this.hoverAction !== 'disabled') {
      this._currentClassList.push('ml-hoverable-button');
    }
  }

  private _disableHoverAction(): void {
    if (this.hoverAction === 'enabled') {
      this._currentClassList.push('ml-hoverable-button');
    }
  }

  private _haltDisabledEvents(event: Event): void {
    if (this.disabled) {
      event.preventDefault();
      event.stopImmediatePropagation();
    }
  }
}

<ng-content></ng-content>
<span class="ml-button-overlay" #mlRippleOutlet>
  <span class="ml-button-focus"></span>
  <span class="ml-button-hover"></span>
</span>

// react/docs/src/material-lite/react/Button/Button.tsx
import React, { Component, cloneElement } from 'react';
import './Button.scss';

import { Falsy, FalsyObject, DirectiveProps, classNamePipe } from '@material-lite/react-cdk/utils';
import { getRippleConfig, updateRippleConfig, MlRippleCore, RippleConfig } from '../core';
import { disableRipple, updateTheme, DisableRipple, Theme, ComponentBehavior } from '../core/common-behaviors';


export type MlButtonVariant = 'basic' | 'raised' | 'stroked' | 'flat' | 'fab' | 'icon';
export type MlButtonHoverAction = 'enabled' | 'disabled' | 'auto';


export type MlButtonProps =
  DirectiveProps &
  FalsyObject<{
    disabled: boolean;
    variant: MlButtonVariant;
    hoverAction: MlButtonHoverAction;
    wrappedAnchor: boolean;
  }> & DisableRipple.Props & Theme.Props & RippleConfig.Props;

type Behaviors = DisableRipple.Member & Theme.Member & RippleConfig.Member;
type PrivateBehaviors = Theme.PrivateNames | RippleConfig.PrivateNames;

const MlButtonComponent = Component as ComponentBehavior<MlButtonProps, DisableRipple.Method & Theme.Method & RippleConfig.Method>;

class MlButton extends MlButtonComponent implements Behaviors {
  readonly isButtonElement: boolean;

  _classList: Behaviors['_classList'];
  _themeClassIndex = 6;

  readonly rippleCore: MlRippleCore;
  private _rippleCoreFactory: ((outletEl: HTMLElement) => MlRippleCore) | null;

  _defaultRippleConfig: Behaviors['_defaultRippleConfig'] = {
    animation: {
      enter: 280,
      leave: 240
    }
  }

  _rippleConfig: Behaviors['_rippleConfig'] = {
    _dynamic: this._defaultRippleConfig!
  }

  private _overlayElement = (
    <span className="ml-button-overlay" key="ml-button-overlay" ref={this.onLoadRippleOutlet.bind(this)}>
      <span className="ml-button-hover"></span>
      <span className="ml-button-focus"></span>
    </span>
  );

  constructor(props: MlButtonProps) {
    super(props);

    const isButtonEl = this.isButtonElement = props.children.type === 'button';
    if (!isButtonEl) {
      this._haltDisabledEvents = this._haltDisabledEvents.bind(this);
    }

    this._rippleCoreFactory = (outletEl) =>
      new MlRippleCore(this._rippleConfig, true, outletEl);

    this.shouldComponentUpdate(null!);
  }

  onLoadRippleOutlet(ref: HTMLDivElement) {
    if (this._rippleCoreFactory) {
      const props = this.props;

      // @ts-expect-error: Assign to readonly variable
      const core = this.rippleCore = this._rippleCoreFactory(ref);
      this._rippleCoreFactory = null;

      core.presetTrigger(ref.parentElement!);

      if (!(props.disableRipple || props.disabled)) {
        core.setup();
      }
    }
  }

  shouldComponentUpdate(nextProps: MlButtonProps) {
    let needUpdateComponent = false;

    let prevProps: MlButtonProps;

    if (nextProps) {
      prevProps = this.props;

    } else {
      nextProps = this.props
      prevProps = { variant: '' } as any;
    }

    const { variant, hoverAction, disabled, wrappedAnchor } = nextProps;
    if (!(variant === prevProps.variant && hoverAction === prevProps.hoverAction)) {
      if (!variant || variant === 'basic') {
        this._classList = [
          'ml-button',
          'ml-basic-button',
          'ml-simple-button',
          this._enableHoverAction(hoverAction),
          disabled ? 'ml-disabled' : null,
          wrappedAnchor ? 'ml-anchor-button' : null,
        ];
        this._rippleConfig._dynamic.entrance = null;

      } else if (variant === 'raised') {
        this._classList = [
          'ml-button',
          'ml-raised-button',
          'ml-filled-button',
          this._disableHoverAction(hoverAction),
          disabled ? 'ml-disabled' : null,
          wrappedAnchor ? 'ml-anchor-button' : null,
        ];
        this._rippleConfig._dynamic.entrance = null;

      } else if (variant === 'icon') {
        this._classList = [
          'ml-button',
          'ml-icon-button',
          'ml-simple-button',
          this._disableHoverAction(hoverAction),
          disabled ? 'ml-disabled' : null,
          wrappedAnchor ? 'ml-anchor-button' : null,
        ];
        this._rippleConfig._dynamic.entrance = 'center';

      } else if (variant === 'fab') {
        this._classList = [
          'ml-button',
          'ml-fab',
          'ml-filled-button',
          this._disableHoverAction(hoverAction),
          disabled ? 'ml-disabled' : null,
          wrappedAnchor ? 'ml-anchor-button' : null,
        ];
        this._rippleConfig._dynamic.entrance = null;

      } else if (variant === 'flat') {
        this._classList = [
          'ml-button',
          'ml-flat-button',
          'ml-filled-button',
          this._disableHoverAction(hoverAction),
          disabled ? 'ml-disabled' : null,
          wrappedAnchor ? 'ml-anchor-button' : null,
        ];
        this._rippleConfig._dynamic.entrance = null;

      } else if (variant === 'stroked') {
        this._classList = [
          'ml-button',
          'ml-stroked-button',
          'ml-simple-button',
          this._enableHoverAction(hoverAction),
          disabled ? 'ml-disabled' : null,
          wrappedAnchor ? 'ml-anchor-button' : null,
        ];
        this._rippleConfig._dynamic.entrance = null;

      } else {
        this._classList = [
          'ml-button',
          'ml-basic-button',
          'ml-simple-button',
          this._enableHoverAction(hoverAction),
          disabled ? 'ml-disabled' : null,
          wrappedAnchor ? 'ml-anchor-button' : null,
        ];
        this._rippleConfig._dynamic.entrance = null;
      }
      needUpdateComponent = true;

    } else {
      const classList = this._classList;
      if (disabled !== prevProps.disabled) {
        classList[4] = disabled ? 'ml-disabled' : null;
        needUpdateComponent = true;
      }

      if (wrappedAnchor !== prevProps.wrappedAnchor) {
        classList[5] = wrappedAnchor ? 'ml-anchor-button' : null;
        needUpdateComponent = true;
      }
    }

    this.updateRippleConfig(nextProps.rippleConfig, prevProps.rippleConfig);

    if (this.updateTheme(nextProps.theme, prevProps.theme)) needUpdateComponent = true;

    if (this.disableRipple(disabled, prevProps.disabled) === void 0) {
      this.disableRipple(nextProps.disableRipple, prevProps.disableRipple);
    }

    return needUpdateComponent;
  }

  private _enableHoverAction(type: MlButtonHoverAction | Falsy): string | null {
    return type !== 'disabled'
      ? 'ml-hoverable-button'
      : null;
  }

  private _disableHoverAction(type: MlButtonHoverAction | Falsy): string | null {
    return type === 'enabled'
      ? 'ml-hoverable-button'
      : null;
  }

  private _haltDisabledEvents(event: Event): void {
    if (this.props.disabled) {
      event.preventDefault();
      event.stopImmediatePropagation();
    }
  }

  render() {
    const props = this.props;

    const child = props.children;

    let childProps = child.props;

    let grandchildren = childProps?.children;
    grandchildren = grandchildren
      ? [ ...Array.isArray(grandchildren) ? grandchildren : [grandchildren], this._overlayElement ]
      : this._overlayElement

    childProps = childProps
      ? { ...childProps, className: classNamePipe(this._classList, childProps.className) }
      : { className: classNamePipe(this._classList) }

    if (this.isButtonElement) {
      childProps.disabled = props.disabled;

    } else {
      const onClickEvent = childProps.onClick;
      childProps.onClick = onClickEvent
        ? (e: Event) => {
            onClickEvent(e);
            this._haltDisabledEvents(e);
          }
        : this._haltDisabledEvents;
    }

    return cloneElement(child, childProps, grandchildren);
  }
}

(() => {
  const proto = MlButton.prototype;
  proto.disableRipple = disableRipple;
  proto.updateTheme = updateTheme;
  proto.updateRippleConfig = updateRippleConfig;
  proto.getRippleConfig = getRippleConfig;
})();

export default MlButton as new (props: MlButtonProps) => (Omit<MlButton, PrivateBehaviors>);
