// react/docs/src/app/views/cdk/Categories/Categories.tsx
import React from 'react';
import { useHistory } from 'react-router-dom';

import MlCard from '../../../../material-lite/react/Card';

const Categories = () => {
  const history = useHistory();

  const navRoute = (name: string) => {
    history.push('/react/cdk/' + name);
  }

  return (
    <div className="app-categories">
      <h1>Categories</h1>

      <MlCard variant="stroked" onClick={() => navRoute('straight-tracker')}>
        <div className="app-categories-title">Straight-tracker</div>
      </MlCard>

      <div className="ml-card"></div>
      <div className="ml-card"></div>
      <div className="ml-card"></div>
    </div>
  );
}

export default Categories;

// vue3/docs/src/views/CDK/Categories.vue
<template>
<div class="app-categories">
  <h1>CDK</h1>

  <ml-card @click="gotoLink('portal')">
    Portal
  </ml-card>

  <ml-card @click="gotoLink('straight-tracker')">
    Straight Tracker
  </ml-card>
</div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import { useRouter } from 'vue-router';

export default defineComponent({
  setup() {
    const router = useRouter();
    const gotoLink = (path: string) => {
      router.push('/cdk/' + path);
    };

    return { gotoLink }
  }
})
</script>
