// react/docs/src/app/views/guide/GettingStarted/GettingStarted.tsx
import React from 'react'
import DocsViewer, { DocsCode } from 'components/DocsViewer';

type TP = 'install' | 'installForTheming' | 'usageOfComponent' | 'usageOfScssTheme' | 'usageOfCssTheme';
const DOCS_CODE: DocsCode<TP> = {
  install: {
    html: /*html*/`npm install @material-lite/react @material-lite/react-cdk`
  },
  installForTheming: {
    html: /*html*/`npm install sass @material-lite/theming`
  },
  usageOfComponent: {
    jsx: /*jsx*/ `
      import React from 'react';
      import { MlButton } from '@material-lite/react';
      
      export default function App() {
        return (
          <div className="App">
            <MlButton>
              <button>Button</button>
            </MlButton>
          </div>
        )
      }
    `
  },
  usageOfScssTheme: {
    scss: /*css*/`
      @use '@material-lite/angular' as *;

      $material-lite: (
        default: define-light-theme((
          color: $indigo-pink-color
        ))
      );
      
      @include core();
      @include themes();
    `
  },
  usageOfCssTheme: {
    scss: /*css*/`
      @import '@material-lite/theming/prebuilt-themes/indigo-pink.min.css';
    `
  }
}

const GettingStarted = () => (
  <div className="docs-view docs-markdown">
    <h1>Getting Started</h1>

    <h2>Installing</h2>
    <DocsViewer code={DOCS_CODE.install} disableActions></DocsViewer>

    <h3>For theming</h3>
    <DocsViewer code={DOCS_CODE.installForTheming} disableActions></DocsViewer>


    <h2>Usage of Component</h2>
    <p>例として、<code>App.jsx</code>に<code>MlButton</code>コンポーネントを読み込んでみます。</p>
    <DocsViewer code={DOCS_CODE.usageOfComponent} disableActions></DocsViewer>
    <br></br>
    
    <p>
      次に、<code>src</code>ディレクトリ直下の<code>index.scss</code>にテーマの設定と読み込みをしていきます。<br></br>
      <span className="comment"><a href="https://www.npmjs.com/package/sass">Dart Sass</a><code>(npm i sass)</code>が必要になります。</span>
    </p>
    <DocsViewer code={DOCS_CODE.usageOfScssTheme} disableActions></DocsViewer>
    <br></br>

    <p>もし、<code>Scss (<a href="https://www.npmjs.com/package/sass">Dart Sass</a>)</code>を用いらない場合は、事前に用意された<span className="eng">CSS</span>ファイルを読み込むことでテーマを使用できます。</p>
    <DocsViewer code={DOCS_CODE.usageOfCssTheme} disableActions></DocsViewer>

  </div>
)

export default GettingStarted;

// angular/docs/src/app/views/guide/getting-started/getting-started.component.ts
import { Component } from '@angular/core';
import { DocsCode } from 'src/app/components/docs-viewer';

type TD = 'install' | 'usageTypescript' | 'usageHtml' | 'usageScss';
const DOCS_CODE: DocsCode<TD> = {
  install: { html: 'npm install @material-lite/angular @material-lite/angular-cdk' },

  usageTypescript: {
    typescript: /*javascript*/`
      import { NgModule } from '@angular/core';
      import { MlButtonModule } from '@material-lite/angular/button';
      
      @NgModule({
        ...
        imports: [
          MlButtonModule,
          ...
        ],
        ...
      })
      export class AppModule {}
    `,
  },

  usageHtml: {
    html: /*html*/`
      <button mlButton theme="primary">Button</button>
    `
  },

  usageScss: {
    scss: /*css*/`
      @use '@material-lite/angular' as *;

      $material-lite: (
        default: define-light-theme((
          color: $indigo-pink-color
        ))
      );
      
      @include core();
      @include themes();
    `
  }

}

@Component({
  selector: 'app-getting-started',
  templateUrl: './getting-started.component.html',
  host: { class: 'docs-view docs-markdown' }
})
export class GettingStartedComponent {
  docsCode = DOCS_CODE;
}

<docs-navbar [routes]="['getting-started']" [routeNames]="['Getting started']"></docs-navbar>

<h1>Getting Started</h1>

<div class="docs-markdown">
  <h2>Install</h2>
  <docs-viewer [code]="docsCode.install" disableActions></docs-viewer>
  
  
  <h2>Usage of Component</h2>
  <p>例として、<code>app.module.ts</code>に<span class="eng">Button</span>コンポーネントを読み込んでみます。<br></p>
  <docs-viewer [code]="docsCode.usageTypescript" disableActions></docs-viewer>
  <br>
  
  <p>次に、<code>app.component.html</code>で、コンポーネントを使用していきます。</p>
  <docs-viewer [code]="docsCode.usageHtml" disableActions></docs-viewer>
  <br>
  
  <p>次に、<code>src</code>ディレクトリ直下の<code>styles.scss</code>で、コンポーネントのスタイルを設定します。</p>
  <p>今回は一例として<span class="eng">Scss</span>を用いていますが、<span class="eng">CSS</span>でも行えます。詳しくは<a routerLink="/guide/theming/overview">こちら</a>。</p>
  <docs-viewer [code]="docsCode.usageScss" disableActions></docs-viewer>
  <br>
  
  <p><code>ng serve</code>をterminalに打ち込み、<a href="http://localhost:4200" target="_blank" rel="noopener noreferrer">http://localhost:4200</a>にアクセスし、実際に表示されているかを確認してみましょう。</p>
  
  
  <h2>Next steps</h2>
  <ul>
    <li><a routerLink="/guide/theming/overview">テーマについて詳しく知る</a></li>
    <li><a routerLink="/guide/theming/your-own-themes">テーマをカスタマイズして柔軟に活用する</a></li>
    <li><a routerLink="/guide/elevation-styles">要素に高さを表現する</a></li>
    <li><a routerLink="/guide/duplicates-styles">スタイルの重複について知る</a></li>
  </ul>  
</div>
