// angular/docs/src/app/components/docs-navbar/docs-navbar.component.ts
import { ChangeDetectionStrategy, Component, Input, OnInit, OnDestroy, ViewEncapsulation } from '@angular/core';
import { Router } from '@angular/router';
import { Subscription } from 'rxjs';
import { YoungestRoute } from 'src/app/services/route';

@Component({
  selector: 'docs-navbar',
  templateUrl: './docs-navbar.component.html',
  encapsulation: ViewEncapsulation.None,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    'class': 'docs-navbar'
  }
})
export class DocsNavbarComponent implements OnInit, OnDestroy {
  @Input() routes: string[] = ['overview', 'reference', 'example'];
  @Input() routeNames: string[] = ['Overview', 'Reference', 'Example']

  activatedRoute: string;
  activatedRouteIndex: number;

  private _subscription: Subscription;

  constructor(
    private _router: Router,
    private _youngestRoute: YoungestRoute
  ) {}

  ngOnInit(): void {
    this.onChangeRoute();
    this._subscription =
      this._youngestRoute.routeChanges.subscribe(this.onChangeRoute.bind(this));
  }

  ngOnDestroy(): void {
    this._subscription.unsubscribe();
  }

  onChangeRoute(): void {
    const state = this._youngestRoute.state;

    const currRoute = this.activatedRoute = state.routeConfig!.path!;
    this.activatedRouteIndex = this.routes.indexOf(currRoute);
  }

  goToLink(route: string): void {
    window.scrollTo({top:0});
    const router = this._router;

    const urlArr: string[] = router.url.split('/');
    urlArr[urlArr.length - 1] = route;

    const entryRoute = urlArr.join('/');

    router.navigate([entryRoute]);
  }
}

<ml-straight-tracker
  [targetIndex]="activatedRouteIndex"
  [transition]="{ duration: '400ms', property: 'left' }"
  [transitionClasses]="{ initializing: true }"
>
  <div class="docs-navbar-tracker ml-primary-bg"></div>
</ml-straight-tracker>

<button
  *ngFor="let route of routes; let i = index;"
  class="docs-navbar-button"
  mlButton [theme]="route === activatedRoute ? 'primary' : ''"
  (click)="goToLink(route)"
>
  {{ routeNames[i] }}
</button>

// react/docs/src/app/components/DocsNavbar/DocsNavbar.tsx
import React from 'react';
import { useState } from 'react';
import { useEffect } from 'react';
import { useHistory } from 'react-router-dom';
import StraightTracker from '../../../material-lite/react-cdk/StraightTracker';
import MlButton from '../../../material-lite/react/Button';

interface Props {
  routes?: string[];
  routeNames?: string[];
}

const DEFAULT_ROUTES = ['overview', 'reference', 'examples'];
const DEFAULT_ROUTE_NAMES = ['Overview', 'Reference', 'Examples'];

const DocsNavbar = (props: Props) => {
  const [activatedRoute, setActivatedRoute] = useState<string>();
  const [activatedRouteIndex, setActivatedRouteIndex] = useState<number>();

  const history = useHistory();

  const onChangeRoute = () => {
    const urls: string[] = history.location.pathname.split('/');
    const pathname = urls[urls.length - 1];

    setActivatedRoute(pathname);
    setActivatedRouteIndex((props.routes || DEFAULT_ROUTES).indexOf(pathname));
  }

  /* eslint-disable react-hooks/exhaustive-deps */
  useEffect(onChangeRoute, []);
  useEffect(onChangeRoute, [history.location])
  /* eslint-enable react-hooks/exhaustive-deps */

  const goToLink = (route: string) => {
    window.scrollTo({top:0});

    const urlArr: string[] = history.location.pathname.split('/');
    urlArr[urlArr.length - 1] = route;

    history.push(urlArr.join('/'));
  }

  return (
    <div className="docs-navbar">
      <StraightTracker targetIndex={activatedRouteIndex}>
        <span className="docs-navbar-tracker ml-primary-background"></span>
      </StraightTracker>

      {
        (props.routes || DEFAULT_ROUTES).map((route, i) => (
          <MlButton theme={route === activatedRoute ? 'primary' : ''} key={i}>
            <button onClick={() => goToLink(route)} className="docs-navbar-button">
              { (props.routeNames || DEFAULT_ROUTE_NAMES)[i] }
            </button>
          </MlButton>
        ))
      }
    </div>
  )
}

export default DocsNavbar;
