// react/docs/src/app/views/Home/Home.tsx
import React from 'react';
import './Home.scss';

import MlButton from '../../../material-lite/react/Button';
import { VERSION } from '../../../material-lite/react-cdk/utils';
import { Link } from 'react-router-dom';

const Home = () => {
  return(
    <div className="home">
      <header className="home-header ml-primary-style">
        <h1>
          <span className="home-heading-ml">Material Lite</span>
          <span className="home-heading-for ml-accent-color">for</span>
          <span className="home-heading-angular">React</span>
        </h1>

        <span className="home-heading-version">v{ VERSION }</span>
        <MlButton variant="raised">
          <Link to="/react/guide/getting-started" className="home-heading-button">Get started</Link>
        </MlButton>
      </header>

      <div className="home-body">
        <section className="home-section">
          <h2 className="home-section-heading">インストール</h2>
          <div className="home-docs-codeblock">
            <pre className="prism"><code>npm install @material-lite/react @material-lite/react-cdk</code></pre>
          </div>
        </section>

        <section className="home-section">
          <h2 className="home-section-heading">概要</h2>
          <p><span className="eng ml-accent-color">Material Lite for Angular</span>をベースにした、<span className="eng">React</span>用のコンポーネントライブラリです。</p>
          <p>デザインや機能は<span className="eng ml-accent-color">Angular Material</span>を参考にさせてもらっています。</p>
        </section>
      </div>
    </div>
  )
};

export default Home;

// angular/docs/src/app/views/home/home.component.ts
import { ChangeDetectionStrategy, Component, OnInit, ViewEncapsulation } from '@angular/core';
import { VERSION } from 'src/material-lite/angular-cdk/utils';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.scss'],
  encapsulation: ViewEncapsulation.None,
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class HomeComponent implements OnInit {
  version = VERSION
  constructor() { }
  ngOnInit(): void { }
}

<header class="home-header ml-primary-style">
  <h1>
    <span class="home-heading-ml">Material Lite</span>
    <span class="home-heading-for ml-accent-color">for</span>
    <span class="home-heading-angular">Angular</span>
  </h1>

  <span class="home-heading-version">v{{ version }}</span>
  <button class="home-heading-button" mlButton variant="raised" routerLink="/guide/getting-started">Get started</button>
</header>

<div class="home-body">
  <section class="home-section">
    <h2 class="home-section-heading">インストール</h2>
    <div class="home-docs-codeblock">
      <pre class="prism"><code>npm install @material-lite/angular @material-lite/angular-cdk</code></pre>
    </div>
  </section>
  
  <section class="home-section">
    <h2 class="home-section-heading">概要</h2>
    <p class="home-section-text"><code class="ml-primary-color">Material lite</code>は不要なレンダリングの削減に尽力し、<code class="ml-accent-color">Theme</code>を柔軟にカスタマイズできるように作成しています。</p>
    <p class="home-section-text">デザインや機能は<code class="ml-accent-color">Angular Material</code>を参考にさせてもらっています。</p>
  </section>
</div>
