// angular/docs/src/app/views/guide/categories/categories.component.ts
import { Component, ViewEncapsulation } from '@angular/core';

@Component({
  selector: 'app-categories',
  templateUrl: './categories.component.html',
  encapsulation: ViewEncapsulation.None,
  host: {'class': 'docs-view'}
})
export class CategoriesComponent {
}

<docs-navbar [routes]="['categories']" [routeNames]="['Categories']"></docs-navbar>

<h1>Guide</h1>

<div class="docs-categories">
  <ml-card variant="stroked" routerLink="/guide/getting-started">
    <h2>Getting started</h2>
  </ml-card>
  
  <ml-card variant="stroked" routerLink="/guide/theming/overview">
    <h2>Theming</h2>
  </ml-card>
  
  <ml-card variant="stroked" routerLink="/guide/elevation-styles">
    <h2>Elevation styles</h2>
  </ml-card>
  
  <ml-card variant="stroked" routerLink="/guide/duplicate-styles">
    <h2>Duplicate styles</h2>
  </ml-card>
  
  <div class="ml-card"></div>
  <div class="ml-card"></div>  
</div>

// react/docs/src/app/views/guide/Categories/Categories.tsx
import React from 'react';
import { useHistory } from 'react-router-dom';

import MlCard from '../../../../material-lite/react/Card';

const Categories = () => {
  const history = useHistory();

  const navRoute = (name: string) => {
    history.push('/react/guide/' + name);
  }

  return (
    <div className="app-categories">
      <h1>Guide</h1>

      <MlCard variant="stroked" onClick={() => navRoute('getting-started')}>
        <div className="app-categories-title">Getting started</div>
      </MlCard>

      <MlCard variant="stroked" onClick={() => navRoute('theming')}>
        <div className="app-categories-title">Theming</div>
      </MlCard>

      <MlCard variant="stroked" onClick={() => navRoute('elevation-styles')}>
        <div className="app-categories-title">Elevation styles</div>
      </MlCard>

      <MlCard variant="stroked" onClick={() => navRoute('duplicate-styles')}>
        <div className="app-categories-title">Duplicate styles</div>
      </MlCard>

      <div className="ml-card"></div>
      <div className="ml-card"></div>
    </div>
  );
}

export default Categories;
