// angular/docs/src/_docs-template/pages/reference.component.ts
import { Component } from '@angular/core';
import { DocsCode } from 'src/app/components/docs-viewer';

type TD = 'importing' | 'inputDirectives';
const DOCS_CODE: DocsCode<TD> = {
  importing: {
    typescript: `import { NAME } from '@material-lite/angular/name';`
  },

  inputDirectives: {
    typescript: /*javascript*/`
    `
  }
};
@Component({
  selector: 'app-reference',
  templateUrl: './reference.component.html',
  host: { class: 'docs-reference' }
})
export class ReferenceComponent {
  docsCode = DOCS_CODE;
  constructor() {}
}

<docs-viewer [code]="docsCode.importing" disableActions></docs-viewer>

<h2>NAME</h2>
<h5>
  <code>selector: <span>[name]</span></code>
  <code>exportAs: <span>mlNAME</span></code>
</h5>

<div class="desc-block">
  <h3>Directives</h3>
  <h4>@Input</h4>
  <table>
    <tr>
      <th>Selector</th>
      <th>Variable</th>
      <th>Description</th>
    </tr>
  
    <tr>
      <td>selector</td>
      <td></td>
      <td>特になし。</td>
    </tr>
  </table>
  <docs-viewer [code]="docsCode.inputDirectives" disableActions></docs-viewer>
</div>

// react/docs/src/app/views/components/Button/pages/Reference.tsx
import React from 'react';
import DocsViewer, { DocsCode } from 'components/DocsViewer';

type TP = 'importing';
const DOCS_CODE: DocsCode<TP> = {
  importing: {
    typescript: /*javascript*/`import { MlButton } from '@material-lite/react';`
  }
}
export const Reference = () => (
  <div className="docs-reference">
    <DocsViewer code={DOCS_CODE.importing} disableActions></DocsViewer>

    <h2>製作中</h2>
  </div>
)
