// react/docs/src/app/views/guide/Theming/pages/Overview.tsx
import React from 'react';
import DocsViewer, { DocsCode } from 'components/DocsViewer';

type TP = 'overview';
const DOCS_CODE: DocsCode<TP> = {
  overview: {
    jsx: /*jsx*/`
    
    `
  }
}

export const Overview = () => (
  <div className="docs-markdown">
    <h2>Overview</h2>
    <h4>
      Themingの方法に関しては、Angularと共通なので、<a  href="https://material-lite.web.app/angular/guide/theming" target="_blank" rel="noopener noreferrer">こちらのページ</a>を参考にしてください。<br/>
      近々、Theming専用のページを公開しようと思います。
    </h4>
  </div>
)

// angular/docs/src/app/views/guide/theming/pages/overview.component.ts
import { Component } from '@angular/core';
import { DocsCode } from 'src/app/components/docs-viewer';

type TD = 'preparation';
const DOCS_CODE: DocsCode<TD> = {
  preparation: {
    typescript: /*javascript*/`
    import { Component } from '@angular/core';
    import { MlTheming } from '@material-lite/angular/core';
    `
  }
};
@Component({
  selector: 'app-overview',
  templateUrl: './overview.component.html',
  host: { class: 'docs-markdown' }
})
export class OverviewComponent {
  docsCode = DOCS_CODE;
  constructor() {}
}

<h2>Overview</h2>
<p>
  <span class="eng">Material Lite</span>でコンポーネントを使用する際は、いずれかの<code>CSS</code>もしくは<code>Sass</code>を用いてテーマを設定する必要があります。
  テーマに関しては、このコンポーネントの参考元の<a href="https://github.com/junpei10/material-lite" target="_blank" rel="noopener noreferrer"><span class="eng">Angular Material</span></a>と、
  Googleの<a href="https://material.io/design/material-theming/overview.html"><span class="eng">Material Design</span></a>に基づいて制作しています。
</p>
<p>このページでは主に、<code>Dart Sass</code>を用いたテーマの設定方法を解説します。</p>
<p><code>typography</code>の設定に関して、現在は未対応ですが、後に実装する予定です。</p>

<h3>Dart Sass</h3>
<p><span class="eng">Material Lite</span>のテーマ設定は、<code>CSS</code>でも可能ですが、<code>Dart Sass</code>を用いて行うことをお勧めします。</p>
<p><code>Dart Sass</code>を用いることで、複数のテーマを設定できたり、<code>Mixin</code>や<code>Function</code>を用いて簡単にスタイルを追加できたりなど、テーマ設定における柔軟性を最大限に引き出すことが可能になります。</p>
