// react/docs/src/app/views/guide/Theming/pages/YourOwnThemes.tsx
import React from 'react';
import DocsViewer, { DocsCode } from 'components/DocsViewer';

type TP = 'overview';
const DOCS_CODE: DocsCode<TP> = {
  overview: {
    jsx: /*jsx*/`
    
    `
  }
}

export const YourOwnThemes = () => (
  <div className="docs-markdown">
    <h2>Your <span className="ml-accent-color">own</span> themes</h2>
    <h4>
      Themingの方法に関しては、Angularと共通なので、<a  href="https://material-lite.web.app/angular/guide/theming/your-own-themes" target="_blank" rel="noopener noreferrer">こちらのページ</a>を参考にしてください。<br/>
      近々、Theming専用のページを公開しようと思います。
    </h4>
  </div>
)

// angular/docs/src/app/views/guide/theming/pages/your-own-themes.component.ts
import { Component } from '@angular/core';
import { DocsCode } from 'src/app/components/docs-viewer';

type TD = 'preparingExample' | 'preparingExample2' | 'preparingExample3';
const DOCS_CODE: DocsCode<TD> = {
  preparingExample: {
    scss: /*css*/`
      @forward '@material-lite/angular';
      @use '@material-lite/angular' as *;

      $material-lite: (
        default: define-light-theme((
          color: $indigo-pink-color
        ));
      )
    `
  },

  preparingExample2: {
    scss: /*css*/`
      @use 'src/app/app.theme' as ml;

      @include ml.core();
      @include ml.theme();
    `
  },

  preparingExample3: {
    scss: /*css*/`
      @use 'src/app/app.theme' as ml;

      .example-status-bar {
        /* Styling method */
        @include ml.style(background-color, (background, status-bar));
        
        padding: 16px;
        font-weight: 500;
      }
    `
  }
};
@Component({
  selector: 'app-your-own-themes',
  templateUrl: './your-own-themes.component.html',
  styleUrls: ['./your-own-themes.component.scss'],
  host: { class: 'docs-markdown' }
})
export class YourOwnThemesComponent {
  docsCode = DOCS_CODE;
  constructor() {}
}
<h2>Your <span class="ml-accent-color">own</span> themes</h2>
<p><code>$material-lite</code>グローバル変数を用いて設定することをお勧めしています。</p>


<h2>Preparing a partial file</h2>
<p>
  <code>$material-lite</code>グローバル変数を上書きしたファイルを<a class="eng" href="https://sass-lang.com/guide#topic-4" target="_blank" rel="noopener noreferrer">Partial file</a>として準備し、
  そのファイルを読み込むことで、テーマの設定を共有できるだけでなく、付随した<code>Mixin</code>や<code>Function</code>の引数に<code>$theme</code>などの設定変数を代入する必要が無くなります。
</p>
<h3>Example</h3>
<h4>Partial File</h4>
<code class="file-path">src/app/_app-theme.scss</code>
<docs-viewer [code]="docsCode.preparingExample" disableActions></docs-viewer>

<h4>Entry theme</h4>
<code class="file-path">src/styles.scss</code>
<docs-viewer [code]="docsCode.preparingExample2" disableActions></docs-viewer>

<h4>Example component scss file</h4>
<code class="file-path">src/styles.scss</code>
<docs-viewer [code]="docsCode.preparingExample3" disableActions></docs-viewer>

<h4>Result</h4>
<div class="example-status-bar">Example status bar</div>
